# Site settings
name: Easy Engineering - Blog
title: Easy Engineering - Blog
email: blog@easy-eng.net
description: "Miscellaneous posts from easy-eng.net site."
baseurl: /gh-blog
url: http://da8y01.github.io

# Build settings
markdown: kramdown
permalinks: pretty

highlighter: rouge

analytics:
  provider: google
  google:
    tracking_id : 'UA-78997829-1'
